### ISSUE TITLE
Have constraints in aiger-1.9 been considered？

### ISSUE THREAD

**Issue by gipsyh** [Froleyks/certifaiger#2]
Have constraints in aiger-1.9 been considered？

Some cases with constraints checked failed by certifaiger.

But this case transformed to aiger-1.8 checked passed.

I don't seem to see any handling of constraints in your source code.

**Comment by Froleyks** [comment]
No, constraints and more or less anything not supported in old AIGER is not handled.
This especially includes liveness.
This is currently only a warning, would it have been more expected for you if certifaiger outright fails?

https://github.com/Froleyks/certifaiger/blob/b9e030b7f682a7130a1f8852df8f650cb9fee8f2/src/aiger.hpp#L154

**Comment by gipsyh** [comment]
Yes, I just saw this warning. Will constraint be supported in the future?

**Comment by Froleyks** [comment]
Yes, constraints shouldn't be too difficult.
