### ISSUE TITLE
Checking Property Failed

### ISSUE THREAD

**Issue by gipsyh** [Froleyks/certifaiger#3]
I noticed that Certifai has already supported constraints, but I failed when "checking property"(base and step success), and also aiger1.8 success.
I suspect that there might not be a consideration of constraints during the property check.

**Comment by gipsyh** [comment]
I noticed that the property check is $P' => P$ https://github.com/Froleyks/certifaiger/blob/1c992f1626a15142a1aeb817cd5bfc811690cb38/src/certifaiger.cpp#L262

in my understanding, it might be $C' \land P' => C \land P$

**Comment by Froleyks** [comment]
There are many ways to relax the certificate format in the present of a contraint, i.e., the constraint can be added to other checks as well. However, most of them require QBF checks to be useful. I would like to talk about your application directly. Can you write me an email to nils.froleyks@jku.at
Ideally we can meet directly on WeChat or something.
